export default function Head() {
  return (
    <>
      <title className=" capitalize">
        OpenTable - Find Your Next Table for Best Food
      </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
